//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHolding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public double Volume { get; set; }
        public string Color { get; set; }
        public int Year { get; set; }
        public int Price { get; set; }
        public string ImagePath { get; set; }
        public int TransmissionTypeId { get; set; }
        public int DriveTypeId { get; set; }
        public int BodyTypeId { get; set; }
    
        public virtual BodyType BodyType { get; set; }
        public virtual DriveType DriveType { get; set; }
        public virtual TransmissionType TransmissionType { get; set; }
    }
}
